module HangmanDisplay 
    def tree
        puts " ___________________"
        puts "|"
        puts "|"
        puts "|"
        puts "|"
        puts "|"
        puts "|"
        puts "|"
        puts "|"
        puts "|"
        puts "|"
        puts "|"
        puts "|"
        puts "|"
        puts "|"
    end
    
    def head 
        puts " ___________________"
        puts "|                   |"
        puts "|                 __|__"
        puts "|                |     |"
        puts "|                 -----"
        puts "|"
        puts "|"
        puts "|"
        puts "|"
        puts "|"
        puts "|"
        puts "|"
        puts "|"
        puts "|"
        puts "|"
    end
    
    def body 
        puts " ___________________"
        puts "|                   |"
        puts "|                 __|__"
        puts "|                |     |"
        puts "|                 -----"
        puts "|                   |"
        puts "|                   |"
        puts "|                   |"
        puts "|                   |"
        puts "|                   |"
        puts "|"
        puts "|"
        puts "|"
        puts "|"
        puts "|"
    end
    
    def right_arm
        puts " ___________________"
        puts "|                   |"
        puts "|                 __|__"
        puts "|                |     |"
        puts "|                 -----"
        puts "|                   |______"
        puts "|                   |"
        puts "|                   |"
        puts "|                   |"
        puts "|                   |"
        puts "|"
        puts "|"
        puts "|"
        puts "|"
        puts "|"
    end
    
    def left_arm
        puts " ___________________"
        puts "|                   |"
        puts "|                 __|__"
        puts "|                |     |"
        puts "|                 -----"
        puts "|             ______|______"
        puts "|                   |"
        puts "|                   |"
        puts "|                   |"
        puts "|                   |"
        puts "|"
        puts "|"
        puts "|"
        puts "|"
        puts "|"
    end
    
    def right_leg
        puts " ___________________"
        puts "|                   |"
        puts "|                 __|__"
        puts "|                |     |"
        puts "|                 -----"
        puts "|             ______|______"
        puts "|                   |"
        puts "|                   |"
        puts "|                   |"
        puts "|                   |"
        puts "|                    \\"
        puts "|                     \\"
        puts "|                      \\"
        puts "|"
        puts "|"
    end
    
    def left_leg
        puts " ___________________"
        puts "|                   |"
        puts "|                 __|__"
        puts "|                |     |"
        puts "|                 -----"
        puts "|             ______|______"
        puts "|                   |"
        puts "|                   |"
        puts "|                   |"
        puts "|                   |"
        puts "|                  / \\"
        puts "|                 /   \\"
        puts "|                /     \\"
        puts "|"
        puts "|"
    end
end